### ISSUE TITLE
Query returns deleted document, FindAll does not.

### ISSUE THREAD

**Issue by instanttim** [filebase/Filebase#23]
After deleting a document with the delete() method, the on-disk file is deleted but the query returns an empty document with the removed ID. I've confirmed that using FindAll does NOT return the document though...and manually deleting the cache also seems to fix it.

Note that In both cases i'm returning the document objects, not an array.

$findAll = $projectbase->findAll(TRUE, FALSE);
print_d($findAll);

$allProducts = $projectbase->query()->where('projectType', '=', 'product')->resultDocuments();
print_d($allProducts);

**Comment by instanttim** [comment]
oh, print_d is my own tweak on print_r in case you're wondering. Wraps it in <pre> tags so it formats nicely.

**Comment by timothymarois** [comment]
@instanttim I see. yeah, it looks like the cache is keeping it in the list. You can also disable the cache in the db config if you don't need that. But it looks like I'll need to examine the delete functionality and see if that needs to be removing it from the cache automatically.

**Comment by instanttim** [comment]
I turned the cache off and deleted the directory. The problem is still occurring. Coincidently, documentation says the default value for the cache is false, and the constructor has false in it, but I'm super confused because it was obviously caching even though I hadn't declared that config option.

**Comment by timothymarois** [comment]
@instanttim Ok thanks. Maybe there's something else going on with the cache settings. Nonetheless, I will look into it tonight and see if there's a fix that can be made.

**Comment by timothymarois** [comment]
- Caching was actually set `true` by default. The readme was incorrect. I fixed that. 
- Caching is now cleared when saving/deleting items to keep it from being out of sync.

**Comment by instanttim** [comment]
After updating I'm still seeing this for some amount of time. It seems like it goes away eventually, but turning off the the cache fixes it immediately.

**Comment by instanttim** [comment]
For what it's worth, it returns an object with the same ID and it's got no data in it, but one field that is a valid field name from before it was deleted.

**Comment by timothymarois** [comment]
@instanttim Interesting, I will have to take a look at the tests again. The design was any `update()` or `delete()` methods would clear the cache automatically.
